### All Users By Admin
GET http://localhost:3000/admins/users?pageNumber=1&userPerPage=5&usersName=karim&usersOrder=asc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJrYXJpbS5ib3VhenphQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNzYwNjkzOTE0LCJleHAiOjE3NjA3ODAzMTR9.f_-gZeqxXyT9ll1v1DLt-McC5dATdztAoDmUSXtdgsk

### Get User by ID By Admin
GET http://localhost:3000/admins/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJrYXJpbS5ib3VhenphQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNzYwNTU2Mjc5LCJleHAiOjE3NjA2NDI2Nzl9.M5lZNn8u9SVMD47LsdHlPoXhYDarIBSYOVHhjxB9ouA

### Create User By Admin
POST http://localhost:3000/admins/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJrYXJpbS5ib3VhenphQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNzYwNTUxNTAyLCJleHAiOjE3NjA2Mzc5MDJ9.dQo7u89SXrwHc-vB2RpaRU15GiI1K9sEY9V9syAKLRI

{
  "name": "Me Karim",
  "email": "Me@example.com",
  "password": "StrongPassword123!",
  "role": "Admin"
}

### Update User By Admin
PUT http://localhost:3000/admins/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJrYXJpbS5ib3VhenphQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNzYwNTUxNTAyLCJleHAiOjE3NjA2Mzc5MDJ9.dQo7u89SXrwHc-vB2RpaRU15GiI1K9sEY9V9syAKLRI

{
   "active": false
}

### Delete User By Admin
DELETE http://localhost:3000/admins/2

### Current Admin
GET  http://localhost:3000/admins/currentAdmin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJrYXJpbS5ib3VhenphQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImFjdGl2ZSI6dHJ1ZSwiaWF0IjoxNzYwNTUxNTAyLCJleHAiOjE3NjA2Mzc5MDJ9.dQo7u89SXrwHc-vB2RpaRU15GiI1K9sEY9V9syAKLRI