### Create New Categroy
POST http://localhost:3000/category/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJwcm9mZXNzb3JfdXN0aGJAZXhhbXBsZS5jb20iLCJyb2xlIjoiQWRtaW4iLCJhY3RpdmUiOmZhbHNlLCJpYXQiOjE3NjIwODU5ODEsImV4cCI6MTc2MjE3MjM4MX0.DunMhMWUnGLdOnVS8tcP_QTExRDIMiremWYerHn3t-c

{
  "name": "Clothes"
}

### Get All Categories
GET http://localhost:3000/category/categories

### Get Category By Id
GET http://localhost:3000/category/2

### Updated Category by Id
PUT http://localhost:3000/category/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJwcm9mZXNzb3JfdXN0aGJAZXhhbXBsZS5jb20iLCJyb2xlIjoiQWRtaW4iLCJhY3RpdmUiOmZhbHNlLCJpYXQiOjE3NjIwODU5ODEsImV4cCI6MTc2MjE3MjM4MX0.DunMhMWUnGLdOnVS8tcP_QTExRDIMiremWYerHn3t-c

{
  "name": "hwayj"
}

### Delete Category By Id
DELETE http://localhost:3000/category/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJwcm9mZXNzb3JfdXN0aGJAZXhhbXBsZS5jb20iLCJyb2xlIjoiQWRtaW4iLCJhY3RpdmUiOmZhbHNlLCJpYXQiOjE3NjIwODU5ODEsImV4cCI6MTc2MjE3MjM4MX0.DunMhMWUnGLdOnVS8tcP_QTExRDIMiremWYerHn3t-c