### Send Mail
POST http://localhost:3000/reset-password/send-email
Content-Type: application/json

{
  "email": "karim19215@gmail.com"
}

### Code Verification
POST http://localhost:3000/reset-password/verify-code?email=karim19215@gmail.com&pes=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJrYXJpbTE5MjE1QGdtYWlsLmNvbSIsInJvbGUiOiJVc2VyIiwiYWN0aXZlIjp0cnVlLCJpYXQiOjE3NjExNTgyOTIsImV4cCI6MTc2MTI0NDY5Mn0.Xva-cCH0zZBKUQs8Yp9I9ucXOF6UK4h5lx_Hx7GANSw
Content-Type: application/json

{ 
  "code": "636826"
}

### Reset Password
POST http://localhost:3000/reset-password/reset?email=karim19215@gmail.com&pes=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJrYXJpbTE5MjE1QGdtYWlsLmNvbSIsInJvbGUiOiJVc2VyIiwiYWN0aXZlIjp0cnVlLCJpYXQiOjE3NjExNTgyOTIsImV4cCI6MTc2MTI0NDY5Mn0.Xva-cCH0zZBKUQs8Yp9I9ucXOF6UK4h5lx_Hx7GANSw
Content-Type: application/json

{
  "code": "636826",
  "password": "StrongPassword123!kq"
}